### ISSUE TITLE
Arduino R4 Wifi Error - WifiS3.h : No such file or directory

### ISSUE THREAD

**Issue by Tailslide** [arduino-libraries/Arduino_ConnectionHandler#100] opened 2023-08-13 20:22 UTC
Trying to use this library on an Uno R4 Wifi and I get this compile error:

```
Processing uno_r4_wifi (platform: renesas-ra; framework: arduino; board: uno_r4_wifi)
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------Verbose mode can be enabled via `-v, --verbose` option
CONFIGURATION: https://docs.platformio.org/page/boards/renesas-ra/uno_r4_wifi.html
PLATFORM: Renesas RA (1.1.0) > Arduino Uno R4 WiFi    
HARDWARE: RA4M1 48MHz, 32KB RAM, 256KB Flash
DEBUG: Current (cmsis-dap) External (cmsis-dap, jlink)
PACKAGES:
 - framework-arduinorenesas-uno @ 1.0.2
 - tool-bossac @ 1.10901.0 (1.9.1)
 - toolchain-gccarmnoneeabi @ 1.100301.220327 (10.3.1)
LDF: Library Dependency Finder -> https://bit.ly/configure-pio-ldf
LDF Modes: Finder ~ chain, Compatibility ~ soft
Found 30 compatible libraries
Scanning dependencies...
Dependency Graph
|-- ArduinoIoTCloud @ 1.12.0
|-- Arduino_ConnectionHandler @ 0.7.6
Building in release mode
Compiling .pio\build\uno_r4_wifi\src\Blink.cpp.o
Compiling .pio\build\uno_r4_wifi\lib2f1\Arduino_ConnectionHandler\Arduino_ConnectionHandler.cpp.o
Compiling .pio\build\uno_r4_wifi\lib2f1\Arduino_ConnectionHandler\Arduino_EthernetConnectionHandler.cpp.o
Compiling .pio\build\uno_r4_wifi\lib2f1\Arduino_ConnectionHandler\Arduino_GSMConnectionHandler.cpp.o
Compiling .pio\build\uno_r4_wifi\lib2f1\Arduino_ConnectionHandler\Arduino_LoRaConnectionHandler.cpp.o
Compiling .pio\build\uno_r4_wifi\lib2f1\Arduino_ConnectionHandler\Arduino_NBConnectionHandler.cpp.o
Compiling .pio\build\uno_r4_wifi\lib2f1\Arduino_ConnectionHandler\Arduino_WiFiConnectionHandler.cpp.o
Compiling .pio\build\uno_r4_wifi\lib68b\ArduinoIoTCloud\ArduinoIoTCloud.cpp.o
Compiling .pio\build\uno_r4_wifi\lib68b\ArduinoIoTCloud\ArduinoIoTCloudLPWAN.cpp.o
Compiling .pio\build\uno_r4_wifi\lib68b\ArduinoIoTCloud\ArduinoIoTCloudTCP.cpp.o
Compiling .pio\build\uno_r4_wifi\lib68b\ArduinoIoTCloud\cbor\CBORDecoder.cpp.o
Compiling .pio\build\uno_r4_wifi\lib68b\ArduinoIoTCloud\cbor\CBOREncoder.cpp.o
Compiling .pio\build\uno_r4_wifi\lib68b\ArduinoIoTCloud\cbor\lib\tinycbor\src\cborencoder.c.o
Compiling .pio\build\uno_r4_wifi\lib68b\ArduinoIoTCloud\cbor\lib\tinycbor\src\cborencoder_close_container_checked.c.o
Compiling .pio\build\uno_r4_wifi\lib68b\ArduinoIoTCloud\cbor\lib\tinycbor\src\cborerrorstrings.c.o
Compiling .pio\build\uno_r4_wifi\lib68b\ArduinoIoTCloud\cbor\lib\tinycbor\src\cborparser.c.o
Compiling .pio\build\uno_r4_wifi\lib68b\ArduinoIoTCloud\cbor\lib\tinycbor\src\cborparser_dup_string.c.o
Compiling .pio\build\uno_r4_wifi\lib68b\ArduinoIoTCloud\cbor\lib\tinycbor\src\cborpretty.c.o
Compiling .pio\build\uno_r4_wifi\lib68b\ArduinoIoTCloud\cbor\lib\tinycbor\src\cborpretty_stdio.c.o
Compiling .pio\build\uno_r4_wifi\lib68b\ArduinoIoTCloud\cbor\lib\tinycbor\src\cbortojson.c.o
Compiling .pio\build\uno_r4_wifi\lib68b\ArduinoIoTCloud\cbor\lib\tinycbor\src\cborvalidation.c.o
In file included from .pio\libdeps\uno_r4_wifi\Arduino_ConnectionHandler\src\Arduino_EthernetConnectionHandler.h:22,
                 from .pio\libdeps\uno_r4_wifi\Arduino_ConnectionHandler\src\Arduino_EthernetConnectionHandler.cpp:19:
.pio\libdeps\uno_r4_wifi\Arduino_ConnectionHandler\src\Arduino_ConnectionHandler.h:151:12: fatal error: WiFiS3.h: No such file or directory
```

**Comment by per1234** [comment] 2023-08-14 06:24
Hi @Tailslide. The "**WiFiS3**" library that provides `WiFiS3.h` is bundled with the "**Arduino UNO R4 Boards**" platform of the UNO R4 WiFi:

https://github.com/arduino/ArduinoCore-renesas/tree/main/libraries/WiFiS3

This file will always be available when compiling for the UNO R4 WiFi using the official Arduino development tools. So the cause of the error must be one of the following:

- Some misconfiguration of your system
- A misconfiguration of your PlatformIO project
- A bug or deficiency in [the "Renesas RA" PlatformIO platform](https://registry.platformio.org/platforms/platformio/renesas-ra)

Any of those are out of scope for this issue tracker so I'll close this as off topic. I suggest you request assistance over on [the PlatformIO forum](https://community.platformio.org/). If you discover the cause is a bug in the "Renesas RA" PlatformIO platform, you can then submit a report to the issue tracker of that project:

https://github.com/platformio/platform-renesas-ra/issues

**Closed by per1234** 2023-08-14 06:24 UTC
Labels: type: imperfection
